version: "3.8"
services: 
    bot:
        build: .
        ports:
            - "443:443"
        environment:
            - DISCORD_MAIN_TOKEN
            - TENOR_TOKEN

    postgres:
        image: postgres:13.0
        restart: always
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            PGDATA: "/bot/database"
        volumes:
            - /var/postgres:/bot/database
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080